name: CI/CD TaskFlow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  ACR_LOGIN_SERVER: taskflowacr.azurecr.io
  BACKEND_IMAGE: taskflow-backend
  FRONTEND_IMAGE: taskflow-frontend

jobs:

  build-and-test:
    name: Testar e construir aplicação
    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        working-directory: ./backend
        run: npm ci

      - name: Verificar JavaScript
        working-directory: ./backend
        run: node --check src/server.js

      - name: Validar Docker Compose
        run: docker compose config

      - name: Construir imagem do backend
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$BACKEND_IMAGE:${{ github.sha }} \
            ./backend

      - name: Construir imagem do frontend
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:${{ github.sha }} \
            ./frontend

  deploy:
    name: Publicar no Azure
    runs-on: ubuntu-latest
    needs: build-and-test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry
        run: |
          az acr login --name taskflowacr

      - name: Construir imagem do backend
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$BACKEND_IMAGE:${{ github.sha }} \
            ./backend

      - name: Construir imagem do frontend
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:${{ github.sha }} \
            ./frontend

      - name: Enviar imagem do backend
        run: |
          docker push \
            $ACR_LOGIN_SERVER/$BACKEND_IMAGE:${{ github.sha }}

      - name: Enviar imagem do frontend
        run: |
          docker push \
            $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:${{ github.sha }}

      - name: Atualizar Backend
        run: |
          az containerapp update \
            --name taskflow-backend \
            --resource-group taskflow-rg \
            --image $ACR_LOGIN_SERVER/$BACKEND_IMAGE:${{ github.sha }}

      - name: Atualizar Frontend
        run: |
          az containerapp update \
            --name taskflow-frontend \
            --resource-group taskflow-rg \
            --image $ACR_LOGIN_SERVER/$FRONTEND_IMAGE:${{ github.sha }}

      - name: Logout Azure
        run: |
          az logout