name: CI/CD TaskFlow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: Build e enviar imagens Docker
    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        working-directory: ./backend
        run: npm ci

      - name: Verificar código JavaScript
        working-directory: ./backend
        run: node --check src/server.js

      - name: Validar Docker Compose
        run: docker compose config

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: sa-east-1

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir imagem do backend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/taskflow-backend:latest \
            ./backend

      - name: Construir imagem do frontend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/taskflow-frontend:latest \
            ./frontend

      - name: Enviar imagem do backend para ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/taskflow-backend:latest

      - name: Enviar imagem do frontend para ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/taskflow-frontend:latest